---
all:
  children:
    master:
      hosts:
        k3s-master:
    worker:
      hosts:
        k3s-worker-1:
        k3s-worker-2:
        k3s-worker-3:
        k3s-worker-4:
    storage:
      hosts:
        k3s-worker-4:
