---
# Temporary until official helm repo is created for nfs-client-provisioner
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  interval: 5m
