---
- name: kubeconfig | get public ip address
  run_once: true
  register: ip_address
  ipify_facts:
    timeout: 20
- name: kubeconfig | copy config file to local directory
  run_once: true
  fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ inventory_dir | dirname }}/kubeconfig/"
    owner: "{{ lookup('env', 'USER') }}"
    flat: true
- name: kubeconfig | update kubeconfig with the public ip address
  delegate_to: localhost
  become: false
  run_once: true
  replace:
    path: "{{ inventory_dir | dirname }}/kubeconfig/k3s.yaml"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ ip_address.ansible_facts.ipify_public_ip }}:2020"
- name: kubeconfig | update kubeconfig with context name
  delegate_to: localhost
  become: false
  run_once: true
  replace:
    path: "{{ inventory_dir | dirname }}/kubeconfig/k3s.yaml"
    after: "contexts:"
    before: "users:"
    regexp: '^(\s+)name: .*$'
    replace: '\1name: {{ k3s_kubeconfig_context_name }}'
- name: kubeconfig | create directory .kube
  delegate_to: localhost
  become: false
  run_once: true
  file:
    path: ~/.kube
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
- name: kubeconfig | copy config to user home directory
  delegate_to: localhost
  become: false
  run_once: true
  copy:
    src: "{{ inventory_dir | dirname }}/kubeconfig/k3s.yaml"
    dest: "~/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
